import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: "#f4f7fb",
    paddingTop: 12,
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f4f7fb",
    gap: 12,
  },
  loadingText: {
    color: "#334155",
    fontSize: 16,
  },
  header: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  appTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0f172a",
  },
  appSubtitle: {
    fontSize: 13,
    color: "#475569",
    marginTop: 2,
  },
  primaryButton: {
    backgroundColor: "#0f766e",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "600",
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#ffffff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
  },
  secondaryButtonText: {
    color: "#0f172a",
    fontWeight: "600",
    fontSize: 13,
  },
  tabs: {
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
    paddingBottom: 8,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#e2e8f0",
  },
  tabActive: {
    backgroundColor: "#c7f0ec",
  },
  tabText: {
    fontSize: 12,
    color: "#334155",
    fontWeight: "600",
  },
  tabTextActive: {
    color: "#0f766e",
  },
  scroll: {
    paddingHorizontal: 12,
    paddingBottom: 96,
  },
  section: {
    marginBottom: 14,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "700",
  },
  sectionBody: {
    gap: 8,
  },
  statGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  statCard: {
    width: "48%",
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
  },
  statLabel: {
    color: "#64748b",
    fontSize: 12,
  },
  statValue: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "700",
    marginTop: 8,
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
  },
  rowTitle: {
    fontSize: 15,
    color: "#0f172a",
    fontWeight: "600",
  },
  rowSub: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 3,
  },
  rowAmount: {
    fontSize: 14,
    color: "#0f172a",
    fontWeight: "700",
  },
  chevron: {
    fontSize: 20,
    color: "#94a3b8",
    fontWeight: "700",
  },
  risk: {
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },
  risk_green: {
    color: "#166534",
    backgroundColor: "#dcfce7",
  },
  risk_yellow: {
    color: "#92400e",
    backgroundColor: "#fef3c7",
  },
  risk_red: {
    color: "#991b1b",
    backgroundColor: "#fee2e2",
  },
  bodyText: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 20,
  },
  input: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#ffffff",
    color: "#0f172a",
  },
  textArea: {
    minHeight: 84,
    textAlignVertical: "top",
  },
  formField: {
    marginBottom: 12,
  },
  formLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#334155",
    marginBottom: 6,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15, 23, 42, 0.45)",
  },
  sheet: {
    maxHeight: "92%",
    backgroundColor: "#f8fafc",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    gap: 12,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  detailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  detailActions: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  detailTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0f172a",
  },
  detailCard: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 12,
    marginBottom: 12,
  },
  detailCardTitle: {
    fontSize: 16,
    color: "#0f172a",
    fontWeight: "700",
    marginBottom: 8,
  },
  groupBlock: {
    marginBottom: 10,
    gap: 8,
  },
  groupTitle: {
    fontSize: 13,
    color: "#475569",
    fontWeight: "700",
  },
  bottomBar: {
    position: "absolute",
    left: 12,
    right: 12,
    bottom: 12,
    flexDirection: "row",
    gap: 8,
    backgroundColor: "#0f172a",
    borderRadius: 8,
    padding: 8,
  },
  bottomAction: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: "#1e293b",
    alignItems: "center",
  },
  bottomActionText: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 12,
  },
});
